using AIIDEWPF.Models;

namespace AIIDEWPF.Services;

/// <summary>开发语言模板服务 - 涵盖主流 Top 50 编程语言</summary>
public class LanguageTemplateService
{
    private readonly List<LanguageInfo> _languages;

    public LanguageTemplateService() { _languages = BuildLanguageList(); }

    public IReadOnlyList<LanguageInfo> GetAllLanguages() => _languages.AsReadOnly();
    public LanguageInfo? GetByExtension(string ext) =>
        _languages.FirstOrDefault(l => l.FileExtension.Equals(ext, StringComparison.OrdinalIgnoreCase));
    public LanguageInfo? GetByName(string name) =>
        _languages.FirstOrDefault(l => l.Name.Equals(name, StringComparison.OrdinalIgnoreCase));

    private static List<LanguageInfo> BuildLanguageList() => new()
    {
        // ====== Full Support (Top 15) ======
        new() { Name = "Python", FileExtension = ".py", Level = TemplateLevel.Full, FileTemplate = "# Project: {{PROJECT_NAME}}\n\ndef main():\n    print(\"Hello, World!\")\n\nif __name__ == \"__main__\":\n    main()\n", ProjectTemplate = "src/__init__.py|tests/__init__.py|requirements.txt" },
        new() { Name = "JavaScript", FileExtension = ".js", Level = TemplateLevel.Full,
            FileTemplate = "#!/usr/bin/env node\n\n/**\n * Project: {{PROJECT_NAME}}\n */\n\nfunction main() {\n    console.log(\"Hello, World!\");\n}\n\nmain();\n",
            ProjectTemplate = "src/index.js|lib/|package.json" },
        new() { Name = "TypeScript", FileExtension = ".ts", Level = TemplateLevel.Full,
            FileTemplate = "/**\n * Project: {{PROJECT_NAME}}\n */\n\nfunction main(): void {\n    console.log(\"Hello, World!\");\n}\n\nmain();\n",
            ProjectTemplate = "src/index.ts|lib/|tsconfig.json|package.json" },
        new() { Name = "Java", FileExtension = ".java", Level = TemplateLevel.Full,
            FileTemplate = "/**\n * Project: {{PROJECT_NAME}}\n */\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}\n",
            ProjectTemplate = "src/main/java/Main.java|src/main/resources/|build.gradle" },
        new() { Name = "C#", FileExtension = ".cs", Level = TemplateLevel.Full,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nusing System;\n\nclass Program\n{\n    static void Main()\n    {\n        Console.WriteLine(\"Hello, World!\");\n    }\n}\n",
            ProjectTemplate = "src/Program.cs|src/{{PROJECT_NAME}}.csproj" },
        new() { Name = "C++", FileExtension = ".cpp", Level = TemplateLevel.Full,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\n#include <iostream>\n\nint main() {\n    std::cout << \"Hello, World!\" << std::endl;\n    return 0;\n}\n",
            ProjectTemplate = "src/main.cpp|include/|CMakeLists.txt" },
        new() { Name = "C", FileExtension = ".c", Level = TemplateLevel.Full,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\n#include <stdio.h>\n\nint main() {\n    printf(\"Hello, World!\\n\");\n    return 0;\n}\n",
            ProjectTemplate = "src/main.c|include/|Makefile" },
        new() { Name = "Go", FileExtension = ".go", Level = TemplateLevel.Full,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"Hello, World!\")\n}\n",
            ProjectTemplate = "cmd/main.go|internal/|go.mod" },
        new() { Name = "Rust", FileExtension = ".rs", Level = TemplateLevel.Full,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nfn main() {\n    println!(\"Hello, World!\");\n}\n",
            ProjectTemplate = "src/main.rs|Cargo.toml" },
        new() { Name = "PHP", FileExtension = ".php", Level = TemplateLevel.Full,
            FileTemplate = "<?php\n/**\n * Project: {{PROJECT_NAME}}\n */\n\necho \"Hello, World!\";\n",
            ProjectTemplate = "src/index.php|public/|composer.json" },
        new() { Name = "Swift", FileExtension = ".swift", Level = TemplateLevel.Full,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nimport Foundation\n\nprint(\"Hello, World!\")\n",
            ProjectTemplate = "Sources/{{PROJECT_NAME}}/main.swift|Package.swift" },
        new() { Name = "Kotlin", FileExtension = ".kt", Level = TemplateLevel.Full,
            FileTemplate = "/**\n * Project: {{PROJECT_NAME}}\n */\nfun main() {\n    println(\"Hello, World!\")\n}\n",
            ProjectTemplate = "src/main/kotlin/Main.kt|build.gradle.kts" },
        new() { Name = "Ruby", FileExtension = ".rb", Level = TemplateLevel.Full,
            FileTemplate = "#!/usr/bin/env ruby\n# Project: {{PROJECT_NAME}}\n\nputs \"Hello, World!\"\n",
            ProjectTemplate = "lib/{{PROJECT_NAME}}.rb|Gemfile" },
        new() { Name = "R", FileExtension = ".r", Level = TemplateLevel.Full,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nmain <- function() {\n    print(\"Hello, World!\")\n}\n\nmain()\n",
            ProjectTemplate = "R/main.R|DESCRIPTION" },
        new() { Name = "Dart", FileExtension = ".dart", Level = TemplateLevel.Full,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nvoid main() {\n    print('Hello, World!');\n}\n",
            ProjectTemplate = "lib/main.dart|pubspec.yaml" },
        // ====== Basic Support ======
        new() { Name = "Scala", FileExtension = ".scala", Level = TemplateLevel.Basic,
            FileTemplate = "/** Project: {{PROJECT_NAME}} */\nobject Main extends App {\n    println(\"Hello, World!\")\n}\n" },
        new() { Name = "Objective-C", FileExtension = ".m", Level = TemplateLevel.Basic,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n#import <Foundation/Foundation.h>\n\nint main() {\n    @autoreleasepool {\n        NSLog(@\"Hello, World!\");\n    }\n    return 0;\n}\n" },
        new() { Name = "Lua", FileExtension = ".lua", Level = TemplateLevel.Basic,
            FileTemplate = "-- Project: {{PROJECT_NAME}}\n\nlocal function main()\n    print(\"Hello, World!\")\nend\n\nmain()\n" },
        new() { Name = "Shell", FileExtension = ".sh", Level = TemplateLevel.Basic,
            FileTemplate = "#!/bin/bash\n# Project: {{PROJECT_NAME}}\n\necho \"Hello, World!\"\n" },
        new() { Name = "Perl", FileExtension = ".pl", Level = TemplateLevel.Basic,
            FileTemplate = "#!/usr/bin/env perl\n# Project: {{PROJECT_NAME}}\nuse strict;\nuse warnings;\n\nprint \"Hello, World!\\n\";\n" },
        new() { Name = "Haskell", FileExtension = ".hs", Level = TemplateLevel.Basic,
            FileTemplate = "-- Project: {{PROJECT_NAME}}\n\nmain :: IO ()\nmain = putStrLn \"Hello, World!\"\n" },
        new() { Name = "SQL", FileExtension = ".sql", Level = TemplateLevel.Basic,
            FileTemplate = "-- Project: {{PROJECT_NAME}}\n\nSELECT 'Hello, World!' AS greeting;\n" },
        new() { Name = "PowerShell", FileExtension = ".ps1", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nWrite-Host \"Hello, World!\"\n" },
        new() { Name = "MATLAB", FileExtension = ".m", Level = TemplateLevel.Basic,
            FileTemplate = "% Project: {{PROJECT_NAME}}\n\nfunction main()\n    disp('Hello, World!');\nend\n" },
        new() { Name = "Julia", FileExtension = ".jl", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nfunction main()\n    println(\"Hello, World!\")\nend\n\nmain()\n" },
        new() { Name = "Groovy", FileExtension = ".groovy", Level = TemplateLevel.Basic,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nprintln \"Hello, World!\"\n" },
        new() { Name = "Elixir", FileExtension = ".ex", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\ndefmodule Main do\n  def main do\n    IO.puts \"Hello, World!\"\n  end\nend\n\nMain.main()\n" },
        new() { Name = "Clojure", FileExtension = ".clj", Level = TemplateLevel.Basic,
            FileTemplate = ";; Project: {{PROJECT_NAME}}\n\n(defn -main [& args]\n  (println \"Hello, World!\"))\n" },
        new() { Name = "F#", FileExtension = ".fs", Level = TemplateLevel.Basic,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\n[<EntryPoint>]\nlet main argv =\n    printfn \"Hello, World!\"\n    0\n" },
        new() { Name = "Erlang", FileExtension = ".erl", Level = TemplateLevel.Basic,
            FileTemplate = "%% Project: {{PROJECT_NAME}}\n\n-module(main).\n-export([main/0]).\n\nmain() ->\n    io:format(\"Hello, World!~n\").\n" },
        new() { Name = "Fortran", FileExtension = ".f90", Level = TemplateLevel.Basic,
            FileTemplate = "! Project: {{PROJECT_NAME}}\n\nprogram main\n    print *, \"Hello, World!\"\nend program main\n" },
        new() { Name = "COBOL", FileExtension = ".cbl", Level = TemplateLevel.Basic,
            FileTemplate = "      * Project: {{PROJECT_NAME}}\n       IDENTIFICATION DIVISION.\n       PROGRAM-ID. MAIN.\n       PROCEDURE DIVISION.\n           DISPLAY 'Hello, World!'.\n           STOP RUN.\n" },
        new() { Name = "Ada", FileExtension = ".adb", Level = TemplateLevel.Basic,
            FileTemplate = "-- Project: {{PROJECT_NAME}}\n\nwith Ada.Text_IO; use Ada.Text_IO;\n\nprocedure Main is\nbegin\n    Put_Line(\"Hello, World!\");\nend Main;\n" },
        new() { Name = "Prolog", FileExtension = ".pl", Level = TemplateLevel.Basic,
            FileTemplate = "% Project: {{PROJECT_NAME}}\n\nmain :-\n    write('Hello, World!'), nl.\n" },
        new() { Name = "Lisp", FileExtension = ".lisp", Level = TemplateLevel.Basic,
            FileTemplate = ";; Project: {{PROJECT_NAME}}\n\n(defun main ()\n  (format t \"Hello, World!~%\"))\n\n(main)\n" },
        new() { Name = "Scheme", FileExtension = ".scm", Level = TemplateLevel.Basic,
            FileTemplate = ";; Project: {{PROJECT_NAME}}\n\n(display \"Hello, World!\")\n(newline)\n" },
        new() { Name = "Solidity", FileExtension = ".sol", Level = TemplateLevel.Basic,
            FileTemplate = "// SPDX-License-Identifier: MIT\n// Project: {{PROJECT_NAME}}\n\npragma solidity ^0.8.0;\n\ncontract Main {\n    string public greeting = \"Hello, World!\";\n}\n" },
        new() { Name = "Zig", FileExtension = ".zig", Level = TemplateLevel.Basic,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nconst std = @import(\"std\");\n\npub fn main() !void {\n    std.debug.print(\"Hello, World!\\n\", .{});\n}\n" },
        new() { Name = "Nim", FileExtension = ".nim", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nproc main() =\n    echo \"Hello, World!\"\n\nmain()\n" },
        new() { Name = "Crystal", FileExtension = ".cr", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nputs \"Hello, World!\"\n" },
        new() { Name = "OCaml", FileExtension = ".ml", Level = TemplateLevel.Basic,
            FileTemplate = "(* Project: {{PROJECT_NAME}} *)\n\nlet main () =\n    print_endline \"Hello, World!\"\n\nlet () = main ()\n" },
        new() { Name = "D", FileExtension = ".d", Level = TemplateLevel.Basic,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nimport std.stdio;\n\nvoid main() {\n    writeln(\"Hello, World!\");\n}\n" },
        new() { Name = "V", FileExtension = ".v", Level = TemplateLevel.Basic,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nfn main() {\n    println('Hello, World!')\n}\n" },
        new() { Name = "Mojo", FileExtension = ".mojo", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nfn main():\n    print(\"Hello, World!\")\n" },
        new() { Name = "Ballerina", FileExtension = ".bal", Level = TemplateLevel.Basic,
            FileTemplate = "// Project: {{PROJECT_NAME}}\n\nimport ballerina/io;\n\npublic function main() {\n    io:println(\"Hello, World!\");\n}\n" },
        new() { Name = "Raku", FileExtension = ".raku", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nsub MAIN() {\n    say \"Hello, World!\";\n}\n" },
        new() { Name = "CoffeeScript", FileExtension = ".coffee", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nconsole.log \"Hello, World!\"\n" },
        new() { Name = "Reason", FileExtension = ".re", Level = TemplateLevel.Basic,
            FileTemplate = "/* Project: {{PROJECT_NAME}} */\n\nJs.log(\"Hello, World!\")\n" },
        new() { Name = "Elm", FileExtension = ".elm", Level = TemplateLevel.Basic,
            FileTemplate = "-- Project: {{PROJECT_NAME}}\n\nmodule Main exposing (main)\n\nimport Html exposing (text)\n\nmain =\n    text \"Hello, World!\"\n" },
        new() { Name = "HTML", FileExtension = ".html", Level = TemplateLevel.Basic,
            FileTemplate = "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n    <meta charset=\"UTF-8\">\n    <title>{{PROJECT_NAME}}</title>\n</head>\n<body>\n    <h1>Hello, World!</h1>\n</body>\n</html>\n" },
        new() { Name = "CSS", FileExtension = ".css", Level = TemplateLevel.Basic,
            FileTemplate = "/* Project: {{PROJECT_NAME}} */\n\n* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n}\n\nbody {\n    font-family: sans-serif;\n}\n" },
        new() { Name = "YAML", FileExtension = ".yaml", Level = TemplateLevel.Basic,
            FileTemplate = "# Project: {{PROJECT_NAME}}\n\nname: {{PROJECT_NAME}}\nversion: 1.0.0\n" },
        new() { Name = "XML", FileExtension = ".xml", Level = TemplateLevel.Basic,
            FileTemplate = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Project: {{PROJECT_NAME}} -->\n<root>\n</root>\n" },
        new() { Name = "Markdown", FileExtension = ".md", Level = TemplateLevel.Basic,
            FileTemplate = "# {{PROJECT_NAME}}\n\n## Description\n\nTODO\n" },
        new() { Name = "JSON", FileExtension = ".json", Level = TemplateLevel.Basic,
            FileTemplate = "{\n    \"name\": \"{{PROJECT_NAME}}\",\n    \"version\": \"1.0.0\"\n}\n" },
        new() { Name = "Visual Basic .NET", FileExtension = ".vb", Level = TemplateLevel.Basic,
            FileTemplate = "' Project: {{PROJECT_NAME}}\n\nModule Main\n    Sub Main()\n        Console.WriteLine(\"Hello, World!\")\n    End Sub\nEnd Module\n" },
    };
}
